ivory-benchmark/src/main/scala/com/ambiata/ivory/benchmark/DateUtilsBench.scala
ivory-benchmark/src/main/scala/com/ambiata/ivory/benchmark/ReducerBench.scala
ivory-core/src/main/scala/com/ambiata/ivory/core/Date.scala
ivory-core/src/main/scala/com/ambiata/ivory/core/DateTimeUtil.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/DateTimeUtilSpec.scala

This should give a much faster toDays and a more predictable minus days...
Also ditches toSeconds

Replace some dateutils, remove to seconds because it's unused

---

ivory-core/src/main/scala/com/ambiata/ivory/core/Date.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/DatesSpec.scala

Correct Valid Date, add doc

---

ivory-operation/src/main/scala/com/ambiata/ivory/operation/ingestion/mr.scala
ivory-operation/src/main/scala/com/ambiata/ivory/operation/ingestion/thrift/Conversion.scala

Improve error messages for thrift ingest

---

ivory-cli/src/main/scala/com/ambiata/ivory/cli/ingest.scala
ivory-storage/src/main/scala/com/ambiata/ivory/storage/fact/Namespaces.scala
ivory-storage/src/test/scala/com/ambiata/ivory/storage/fact/NamespacesSpec.scala

This is to avoid confusing errors on CDH4 relating to executable permissions

Ensure namespaceSizes only supports directories to avoid bad ingest errors

---

ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/Extraction.scala

@nhibberd does this look right?
/cc  @domdere

Fix extracting to multiple locations/formats

---

README.md

Work-around for the `|` issue

---

doc/design/big-query.md

@markhibberd FYI - as discussed IRL

Notes on requirements for BigQuery support

---

ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/reduction/LatestNReducer.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/reduction/ClockStateSpec.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/reduction/LatestNReducerSpec.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/reduction/ReducerUtil.scala
project/build.scala
project/depend.scala

I'm happy to go through all the specs and add this for all the `Reduction`s

LatestN wasn't idempotent

---

ivory-storage/src/main/scala/com/ambiata/ivory/storage/metadata/DictionaryTextStorageV2.scala
ivory-storage/src/test/scala/com/ambiata/ivory/storage/metadata/DictionaryTextStorageV2Spec.scala

Something that @raronson noticed

Invalidate dictionary with duplicate fields

---

ivory-core/src/test/scala/com/ambiata/ivory/core/arbitraries/ConcreteGroupFeature.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/gen/GenDictionary.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/gen/GenPlus.scala
ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/Chord.scala
ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/squash/SquashDumpJob.scala
ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/squash/SquashJob.scala
ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/squash/SquashReducerLookup.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/squash/SquashReducerLookupSpec.scala

Support squash skew calculation based on additional namespace size

---

ivory-storage/src/main/scala/com/ambiata/ivory/storage/fact/MrFactConverter.scala
ivory-storage/src/test/scala/com/ambiata/ivory/storage/fact/MrFactConverterSpec.scala

Let me know if `MrFactWriter` is a bad idea. If not, are there any "laws" I'm missing?

Introduce MrFactWriter and laws for MrFactConverter

---

ivory-core/src/main/scala/com/ambiata/ivory/core/FeatureIdMappings.scala

@markhibberd I suspect you'll want me to rename the `apply` function.
/cc @raronson

Make FeatureIdIndex an actual value class

---

ivory-core/src/main/scala/com/ambiata/ivory/core/Dictionary.scala
ivory-core/src/main/scala/com/ambiata/ivory/core/Fact.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/FactSpec.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/ValueSpec.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/arbitraries/Arbitraries.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/arbitraries/ConcreteGroupFact.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/arbitraries/FactsWithStatePriority.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/arbitraries/SparseEntities.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/arbitraries/VirtualDictionary.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/gen/GenValue.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/ChordJobSpec.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/ChordSpec.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/SnapshotReducerSpec.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/SnapshotsSpec.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/chord/ChordArbitraries.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/model/ChordModel.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/model/FactModel.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/model/MapReduceSimple.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/model/ModeHandler.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/model/SnapshotModel.scala
project/build.scala

Hopefully this is not a step backwards. I would definitely argue the `SnapshotsSpec` has at least improved. `ChordArbitraries` is still bad, but I think we need to "model" squash too before that's really possible.

Introduce models for snapshot/chord for testing

---

ivory-mr/src/main/scala/com/ambiata/ivory/mr/MutableOption.scala
ivory-mr/src/test/scala/com/ambiata/ivory/mr/MutableOptionSpec.scala

Introduce MutableOption

---

ivory-operation/src/main/scala/com/ambiata/ivory/operation/extraction/snapshot/SnapshotWritable.scala
ivory-operation/src/test/scala/com/ambiata/ivory/operation/extraction/snapshot/SnapshotWritableSpec.scala

Interesting/scary that it's only picked up by the cdh4 build. Not sure if that means it's not actually a problem for cdh5 in distributed mode.

Fix snapshot grouping offset bug

---

ivory-cli/src/main/scala/com/ambiata/ivory/cli/test/dictionaryGen.scala
ivory-cli/src/test/bin/tests/dictionary-metadata/test
ivory-cli/src/test/bin/versions.sh
ivory-cli/src/test/scala/com/ambiata/ivory/cli/test/genDictionarySpec.scala
ivory-core/src/main/scala/com/ambiata/ivory/core/Expression.scala

Still need to figure out a way to deal with the exact commit that results in a version bump.

Introduce dictionary-metadata cli test

---

ivory-cli/src/main/scala/com/ambiata/ivory/cli/main.scala

@FrontierOtr This what you mean?

Switch usage of pirate helper

---

.travis.yml

See the documentation on this feature in the [sbt user guide](http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html)

Use a cache for the ivy repository

---

ivory-cli/src/main/scala/com/ambiata/ivory/cli/main.scala
ivory-cli/src/test/bin/tests/data-regression/test
ivory-core/src/main/scala/com/ambiata/ivory/core/Cluster.scala
ivory-core/src/main/scala/com/ambiata/ivory/core/IvoryConfiguration.scala
ivory-core/src/main/scala/com/ambiata/ivory/core/ShadowRepository.scala
ivory-core/src/test/scala/com/ambiata/ivory/core/IvoryConfigurationTemporary.scala

Not sure if this is what you had in mind @markhibberd.

Add -D to pirate flags for proper parsing

---

guide/example.md
guide/features/data-modeling.md
guide/features/events.md
guide/features/expressions.md
guide/features/states.md
guide/ingest/index.md
guide/ingest/preparing-data.md
guide/ingest/text-eavt.md
guide/ingest/thrift-eavt.md
guide/query/chord.md
guide/query/index.md
guide/query/snapshot.md
guide/query/text-eavt.md
guide/query/text-tabular.md
guide/query/thrift-eavt.md
guide/query/thrift-tabular.md
mkdocs.yml

@charleso @pmwtsn Thought it might be worth just putting this in as a rough skeleton of what we discussed.

Sketching TOC to see what it looks like.

---

guide/install.md

initial commit
